name: Cucumber Service

on:
  push:
    branches:
      - develop

jobs:
  cucumber-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm ci
      - run: npm test
