name: Cucumber Service

on:
  push:
    branches:
      - develop

jobs:
  rtl-test:
    runs-on: ubuntu-16.04

    steps:
      - name: RTL
        uses: actions/checkout@v1
        run: npm ci
          run: npm run jest
  cypress:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
          run: npm ci
          run: npm start
          run: npm run cy:run
      - name: Cypress run
        uses: cypress-io/github-action@v2
