name: Test actions

on:
  push:
    branches:
      - develop

jobs:
  rtl-test:
    runs-on: ubuntu-16.04

    steps:
      - name: RTL
        uses: actions/checkout@v1
      - run: npm ci
      - run: npm run jest
  cypress:
    runs-on: ubuntu-16.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup npm package
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2.7.0
        with:
          start: npm start
          wait-on: "http://localhost:3000"
          config: baseUrl=http://localhost:3000
